name: Windows Kubernetes CSI
on:
  push:
    branches:
    - main

env:
  REGISTRY: ghcr.io

jobs:

  build-containers:
    name: Build CSI Windows Images
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      matrix:
        windows_version: ["2019", "2022"]
        images: [ {image: csi-driver-smb , version: v1.17.0}, {image: livenessprobe , version: v2.15.0}, {image: node-driver-registrar , version: v2.13.0} ]
      fail-fast: false
    runs-on: "windows-${{ matrix.windows_version }}"
    steps:
    - name: Setup Msys2
      uses: msys2/setup-msys2@v2
      with:
        update: false
        path-type: inherit
        release: false
    - run: git config --global core.autocrlf input
    - name: Checkout
      uses: actions/checkout@v4
    - name: Log in to the Github Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: "Docker Build ${{ matrix.images.image }}:${{ matrix.images.version }} Windows ${{ matrix.windows_version }}"
      id: docker_build
      run: |
        echo ${{ matrix.windows_version }}
        CORE_VERSION=${{ matrix.images.version }}
        IMAGE_NAME=${{ matrix.images.image }}
        echo "Building ${IMAGE_NAME} with ${CORE_VERSION}"
        docker build -f ${IMAGE_NAME}/Dockerfile.windows --build-arg OSVERSION=ltsc${{ matrix.windows_version }} --build-arg COREVERSION=${CORE_VERSION} --tag ${IMAGE_NAME}:${{ matrix.windows_version }}-${CORE_VERSION} ${IMAGE_NAME}
        docker tag ${IMAGE_NAME}:${{ matrix.windows_version }}-${CORE_VERSION} ${{ env.REGISTRY }}/${{ github.repository }}-${IMAGE_NAME}:${{ matrix.windows_version }}-${CORE_VERSION}
        docker tag ${IMAGE_NAME}:${{ matrix.windows_version }}-${CORE_VERSION} dtrajd/${IMAGE_NAME}:${{ matrix.windows_version }}-${CORE_VERSION}
        docker push ${{ env.REGISTRY }}/${{ github.repository }}-${IMAGE_NAME}:${{ matrix.windows_version }}-${CORE_VERSION}
        docker push dtrajd/${IMAGE_NAME}:${{ matrix.windows_version }}-${CORE_VERSION}
